name: Tests
on:
  push:

jobs:
  test:
    concurrency:
      group: test-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    services:
      beanstalkd:
        image: ghcr.io/beanstalkd/beanstalkd:latest
        ports:
          - 11300:11300
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install
      - run: bun test
