name: Tests
on:
  push:

    
jobs:
  test:
    concurrency: 
      group: test-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    services:
      beanstalkd:
        image: schickling/beanstalkd
        ports:
          - 11300:11300
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v2
      with:
        version: 8.7.1

    - uses: actions/setup-node@v3
      with:
        node-version: 18.12.1
        cache: "pnpm"

    - run: pnpm i
    - run: pnpm test
